import { Platform } from 'react-native';

export const theme = {
  colors: {
    background: '#f4f7f2',
    backgroundAlt: '#e8efe5',
    surface: '#ffffff',
    surfaceMuted: '#f8faf7',
    surfaceAccent: '#eef5ee',
    border: '#d6e2d1',
    borderStrong: '#b9cdb5',
    text: '#162218',
    textMuted: '#5d7261',
    textSoft: '#7c9080',
    primary: '#2f7f31',
    primaryDark: '#235f25',
    primarySoft: '#dbead9',
    secondary: '#0f5f73',
    secondarySoft: '#dcedf3',
    accent: '#d9902b',
    accentSoft: '#f8e7c8',
    danger: '#c6523c',
    dangerSoft: '#fae2dc',
    success: '#2f7f31',
    successSoft: '#dbead9',
    shadow: 'rgba(24, 38, 27, 0.08)',
    black: '#000000',
    white: '#ffffff',
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 20,
    xl: 28,
    xxl: 36,
  },
  radius: {
    sm: 14,
    md: 20,
    lg: 28,
    pill: 999,
  },
  typography: {
    display: {
      fontSize: 34,
      lineHeight: 40,
      fontWeight: '700' as const,
      letterSpacing: -0.8,
      fontFamily: Platform.select({ ios: 'Avenir Next', android: 'Helvetica', default: undefined }),
    },
    title: {
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '700' as const,
      letterSpacing: -0.6,
      fontFamily: Platform.select({ ios: 'Avenir Next', android: 'Helvetica', default: undefined }),
    },
    heading: {
      fontSize: 22,
      lineHeight: 28,
      fontWeight: '700' as const,
      letterSpacing: -0.4,
    },
    subheading: {
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '600' as const,
    },
    body: {
      fontSize: 15,
      lineHeight: 22,
      fontWeight: '400' as const,
    },
    bodyStrong: {
      fontSize: 15,
      lineHeight: 22,
      fontWeight: '600' as const,
    },
    label: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '600' as const,
      letterSpacing: 0.2,
    },
    caption: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '500' as const,
      letterSpacing: 0.3,
    },
  },
};
